# First Neurons

In [1]:
import numpy as np
import tensorflow as tf

** Set Random Seeds for same results **

In [2]:
np.random.seed(101)
tf.set_random_seed(101)

** Data Setup **

Setting Up some Random Data for Demonstration Purposes

In [3]:
rand_a = np.random.uniform(0,100,(5,5))
rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [4]:
rand_b = np.random.uniform(0,100,(5,1))
rand_b

array([[99.43179012],
       [52.06653967],
       [57.87895355],
       [73.48190583],
       [54.19617722]])

In [5]:
# CONFIRM SAME  RANDOM NUMBERS (EXECUTE SEED IN SAME CELL!) Watch video for explanation
np.random.seed(101)
rand_a = np.random.uniform(0,100,(5,5))
rand_b = np.random.uniform(0,100,(5,1))

### Placeholders

In [6]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

### Operations

In [7]:
add_op = a+b # tf.add(a,b)
mult_op = a*b #tf.multiply(a,b)

### Running Sessions  to create Graphs with Feed Dictionaries

In [8]:
with tf.Session() as sess:
    add_result = sess.run(add_op,feed_dict={a:rand_a,b:rand_b})
    print(add_result)
    
    print('\n')
    
    mult_result = sess.run(mult_op,feed_dict={a:rand_a,b:rand_b})
    print(mult_result)

[[151.07166  156.49855  102.27921  116.58396  167.95949 ]
 [135.45622   82.76316  141.42784  124.22093   71.06043 ]
 [113.30171   93.09215   76.06819  136.43912  154.42728 ]
 [ 96.71727   81.83804  133.83675  146.38118  101.10579 ]
 [122.72681  105.982925  59.044632  67.9831    72.89292 ]]


[[5134.644   5674.25     283.12433 1705.4707  6813.8315 ]
 [4341.8125  1598.267   4652.734   3756.8293   988.94635]
 [3207.8113  2038.1029  1052.7742  4546.9805  5588.1157 ]
 [1707.379    614.02527 4434.989   5356.7773  2029.8555 ]
 [3714.0984  2806.6438   262.76764  747.19855 1013.292  ]]


________________________

________________________

## Example Neural Network

In [9]:
n_features = 10
n_dense_neurons = 3

In [10]:
# Placeholder for x
x = tf.placeholder(tf.float32,(None,n_features))

In [11]:
# Variables for w and b
b = tf.Variable(tf.zeros([n_dense_neurons]))

W = tf.Variable(tf.random_normal([n_features,n_dense_neurons]))

** Operation Activation Function **

In [12]:
xW = tf.matmul(x,W)

In [13]:
z = tf.add(xW,b)

In [14]:
# tf.nn.relu() or tf.tanh()
a = tf.sigmoid(z)

** Variable Intializer! **

In [15]:
init = tf.global_variables_initializer()

In [16]:
with tf.Session() as sess:
    sess.run(init)
    
    layer_out = sess.run(a,feed_dict={x : np.random.random([1,n_features])})

InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(1, 10), b.shape=(10, 3), m=1, n=3, k=10
	 [[node MatMul (defined at <ipython-input-12-9f9e35a31fe1>:1) ]]
  (1) Internal: Blas GEMM launch failed : a.shape=(1, 10), b.shape=(10, 3), m=1, n=3, k=10
	 [[node MatMul (defined at <ipython-input-12-9f9e35a31fe1>:1) ]]
	 [[Sigmoid/_3]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MatMul:
 Placeholder_2 (defined at <ipython-input-10-45bf880077de>:2)	
 Variable_1/read (defined at <ipython-input-11-b758a15c068f>:4)

Input Source operations connected to node MatMul:
 Placeholder_2 (defined at <ipython-input-10-45bf880077de>:2)	
 Variable_1/read (defined at <ipython-input-11-b758a15c068f>:4)

Original stack trace for 'MatMul':
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\ipykernel\kernelapp.py", line 563, in start
    self.io_loop.start()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\asyncio\base_events.py", line 534, in run_forever
    self._run_once()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\asyncio\base_events.py", line 1771, in _run_once
    handle._run()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\ipykernel\kernelbase.py", line 378, in dispatch_queue
    yield self.process_one()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\gen.py", line 225, in wrapper
    runner = Runner(result, future, yielded)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\gen.py", line 714, in __init__
    self.run()
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\IPython\core\interactiveshell.py", line 2855, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in _run_cell
    return runner(coro)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\IPython\core\interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\IPython\core\interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-9f9e35a31fe1>", line 1, in <module>
    xW = tf.matmul(x,W)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2647, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5925, in mat_mul
    name=name)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\dipod\Anaconda3\envs\Udemy\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


In [ ]:
print(layer_out)

We still need to finish off this process with optimization! Let's learn how to do this next.

_____

## Full Network Example

Let's work on a regression example, we are trying to solve a very simple equation:

y = mx + b

y will be the y_labels and x is the x_data. We are trying to figure out the slope and the intercept for the line that best fits our data!

### Artifical Data (Some Made Up Regression Data)

In [ ]:
x_data = np.linspace(0,10,10) + np.random.uniform(-1.5,1.5,10)

In [ ]:
x_data

In [ ]:
y_label = np.linspace(0,10,10) + np.random.uniform(-1.5,1.5,10)

In [ ]:
plt.plot(x_data,y_label,'*')

** Variables **

In [ ]:
np.random.rand(2)

In [ ]:
m = tf.Variable(0.39)
b = tf.Variable(0.2)

### Cost Function

In [ ]:
error = 0

for x,y in zip(x_data,y_label):
    
    y_hat = m*x + b  #Our predicted value
    
    error += (y-y_hat)**2 # The cost we want to minimize (we'll need to use an optimization function for the minimization!)


### Optimizer

In [ ]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
train = optimizer.minimize(error)

### Initialize Variables

In [ ]:
init = tf.global_variables_initializer()

### Create Session and Run!

In [ ]:
with tf.Session() as sess:
    
    sess.run(init)
    
    epochs = 100
    
    for i in range(epochs):
        
        sess.run(train)
        

    # Fetch Back Results
    final_slope , final_intercept = sess.run([m,b])

In [ ]:
final_slope

In [ ]:
final_intercept

### Evaluate Results

In [ ]:
x_test = np.linspace(-1,11,10)
y_pred_plot = final_slope*x_test + final_intercept

plt.plot(x_test,y_pred_plot,'r')

plt.plot(x_data,y_label,'*')

# Great Job!